import type {
  Profile, Mesa, CategoriaProducto, Ingrediente, Producto,
  Pedido, PedidoItem, Pago, Proveedor, RecetaItem
} from './types';

export const mockProfile: Profile = {
  id: 'demo-admin-id',
  nombre: 'Carlos',
  apellido: 'González',
  rol: 'admin',
  activo: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockEmpleados: Profile[] = [
  { id: 'emp-1', nombre: 'María', apellido: 'López', rol: 'moza', activo: true, created_at: '', updated_at: '' },
  { id: 'emp-2', nombre: 'Laura', apellido: 'García', rol: 'moza', activo: true, created_at: '', updated_at: '' },
  { id: 'emp-3', nombre: 'Pedro', apellido: 'Martínez', rol: 'cocina', activo: true, created_at: '', updated_at: '' },
  { id: 'emp-4', nombre: 'Ana', apellido: 'Rodríguez', rol: 'cajero', activo: true, created_at: '', updated_at: '' },
  { id: 'emp-5', nombre: 'Diego', apellido: 'Fernández', rol: 'encargado', activo: true, created_at: '', updated_at: '' },
  mockProfile,
];

export const mockCategorias: CategoriaProducto[] = [
  { id: 'cat-1', nombre: 'Hamburguesas', descripcion: 'Hamburguesas clásicas y especiales', icono: 'beef', color: '#ef4444', orden: 1, activa: true, created_at: '' },
  { id: 'cat-2', nombre: 'Papas', descripcion: 'Papas fritas y al horno', icono: 'wheat', color: '#f59e0b', orden: 2, activa: true, created_at: '' },
  { id: 'cat-3', nombre: 'Bebidas', descripcion: 'Gaseosas, jugos y aguas', icono: 'glass-water', color: '#3b82f6', orden: 3, activa: true, created_at: '' },
  { id: 'cat-4', nombre: 'Postres', descripcion: 'Helados y tortas', icono: 'cake', color: '#ec4899', orden: 4, activa: true, created_at: '' },
  { id: 'cat-5', nombre: 'Combos', descripcion: 'Combos completos con bebida', icono: 'package', color: '#10b981', orden: 5, activa: true, created_at: '' },
  { id: 'cat-6', nombre: 'Extras', descripcion: 'Adicionales y salsas', icono: 'plus-circle', color: '#6366f1', orden: 6, activa: true, created_at: '' },
];

export const mockProveedores: Proveedor[] = [
  { id: 'prov-1', nombre: 'Carnes del Norte', contacto: 'Juan Pérez', telefono: '011-4444-5555', email: 'carnesdelnorte@mail.com', activo: true, created_at: '' },
  { id: 'prov-2', nombre: 'Lácteos San Luis', contacto: 'Roberto Sosa', telefono: '011-3333-4444', email: 'lacteossanluis@mail.com', activo: true, created_at: '' },
  { id: 'prov-3', nombre: 'Verduras Frescas', contacto: 'Elena Mora', telefono: '011-2222-3333', email: 'verdfrescas@mail.com', activo: true, created_at: '' },
  { id: 'prov-4', nombre: 'Distribuidora Bebidas', contacto: 'Carlos Ruiz', telefono: '011-1111-2222', email: 'distr.bebidas@mail.com', activo: true, created_at: '' },
];

export const mockIngredientes: Ingrediente[] = [
  { id: 'ing-1', nombre: 'Carne vacuna', unidad_medida: 'gramos', stock_actual: 8500, stock_minimo: 2000, costo_por_unidad: 0.0144, proveedor_id: 'prov-1', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-2', nombre: 'Pan de hamburguesa', unidad_medida: 'unidad', stock_actual: 120, stock_minimo: 30, costo_por_unidad: 85, proveedor_id: 'prov-3', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-3', nombre: 'Queso cheddar (feta)', unidad_medida: 'feta', stock_actual: 200, stock_minimo: 40, costo_por_unidad: 45, proveedor_id: 'prov-2', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-4', nombre: 'Lechuga', unidad_medida: 'gramos', stock_actual: 3000, stock_minimo: 500, costo_por_unidad: 0.005, proveedor_id: 'prov-3', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-5', nombre: 'Tomate', unidad_medida: 'gramos', stock_actual: 4000, stock_minimo: 800, costo_por_unidad: 0.006, proveedor_id: 'prov-3', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-6', nombre: 'Papas fritas (porción)', unidad_medida: 'porcion', stock_actual: 150, stock_minimo: 30, costo_por_unidad: 210, proveedor_id: 'prov-3', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-7', nombre: 'Coca-Cola 500ml', unidad_medida: 'unidad', stock_actual: 80, stock_minimo: 20, costo_por_unidad: 280, proveedor_id: 'prov-4', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-8', nombre: 'Agua mineral 500ml', unidad_medida: 'unidad', stock_actual: 60, stock_minimo: 15, costo_por_unidad: 120, proveedor_id: 'prov-4', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-9', nombre: 'Salsa especial', unidad_medida: 'porcion', stock_actual: 300, stock_minimo: 50, costo_por_unidad: 15, proveedor_id: 'prov-3', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-10', nombre: 'Panceta ahumada', unidad_medida: 'gramos', stock_actual: 2000, stock_minimo: 400, costo_por_unidad: 0.022, proveedor_id: 'prov-1', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-11', nombre: 'Huevo', unidad_medida: 'unidad', stock_actual: 60, stock_minimo: 12, costo_por_unidad: 35, proveedor_id: 'prov-2', activo: true, created_at: '', updated_at: '' },
  { id: 'ing-12', nombre: 'Cebolla', unidad_medida: 'gramos', stock_actual: 5000, stock_minimo: 1000, costo_por_unidad: 0.003, proveedor_id: 'prov-3', activo: true, created_at: '', updated_at: '' },
];

export const mockRecetaHamburguesaClasica: RecetaItem[] = [
  { id: 'rec-1', producto_id: 'prod-1', ingrediente_id: 'ing-1', cantidad: 180, unidad_medida: 'gramos', costo_calculado: 2.592, created_at: '', ingrediente: mockIngredientes[0] },
  { id: 'rec-2', producto_id: 'prod-1', ingrediente_id: 'ing-2', cantidad: 1, unidad_medida: 'unidad', costo_calculado: 85, created_at: '', ingrediente: mockIngredientes[1] },
  { id: 'rec-3', producto_id: 'prod-1', ingrediente_id: 'ing-3', cantidad: 2, unidad_medida: 'feta', costo_calculado: 90, created_at: '', ingrediente: mockIngredientes[2] },
  { id: 'rec-4', producto_id: 'prod-1', ingrediente_id: 'ing-4', cantidad: 30, unidad_medida: 'gramos', costo_calculado: 0.15, created_at: '', ingrediente: mockIngredientes[3] },
  { id: 'rec-5', producto_id: 'prod-1', ingrediente_id: 'ing-5', cantidad: 40, unidad_medida: 'gramos', costo_calculado: 0.24, created_at: '', ingrediente: mockIngredientes[4] },
  { id: 'rec-6', producto_id: 'prod-1', ingrediente_id: 'ing-9', cantidad: 1, unidad_medida: 'porcion', costo_calculado: 15, created_at: '', ingrediente: mockIngredientes[8] },
];

export const mockProductos: Producto[] = [
  {
    id: 'prod-1',
    nombre: 'Hamburguesa Clásica',
    descripcion: 'Carne 180g, cheddar doble, lechuga, tomate, salsa especial en pan brioche',
    categoria_id: 'cat-1',
    precio_venta: 3500,
    costo_produccion: 1935,
    margen_ganancia: 44.7,
    disponible: true, agotado: false, tiempo_preparacion: 12, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[0],
    receta: mockRecetaHamburguesaClasica,
  },
  {
    id: 'prod-2',
    nombre: 'Hamburguesa Bacon',
    descripcion: 'Carne 180g, cheddar, panceta crocante, cebolla caramelizada, salsa BBQ',
    categoria_id: 'cat-1',
    precio_venta: 4200,
    costo_produccion: 2380,
    margen_ganancia: 43.3,
    disponible: true, agotado: false, tiempo_preparacion: 15, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[0],
  },
  {
    id: 'prod-3',
    nombre: 'Hamburguesa Doble',
    descripcion: 'Doble carne 360g, triple cheddar, lechuga, tomate, pepinillos, mayo',
    categoria_id: 'cat-1',
    precio_venta: 5500,
    costo_produccion: 3200,
    margen_ganancia: 41.8,
    disponible: true, agotado: false, tiempo_preparacion: 18, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[0],
  },
  {
    id: 'prod-4',
    nombre: 'Hamburguesa Veggie',
    descripcion: 'Medallón de legumbres, queso, verduras frescas, salsa verde',
    categoria_id: 'cat-1',
    precio_venta: 3200,
    costo_produccion: 1650,
    margen_ganancia: 48.4,
    disponible: true, agotado: false, tiempo_preparacion: 10, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[0],
  },
  {
    id: 'prod-5',
    nombre: 'Papas Medianas',
    descripcion: 'Papas fritas crocantes con sal y condimentos',
    categoria_id: 'cat-2',
    precio_venta: 1200,
    costo_produccion: 420,
    margen_ganancia: 65,
    disponible: true, agotado: false, tiempo_preparacion: 8, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[1],
  },
  {
    id: 'prod-6',
    nombre: 'Papas Grandes',
    descripcion: 'Porción grande de papas fritas con dips',
    categoria_id: 'cat-2',
    precio_venta: 1800,
    costo_produccion: 630,
    margen_ganancia: 65,
    disponible: true, agotado: false, tiempo_preparacion: 10, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[1],
  },
  {
    id: 'prod-7',
    nombre: 'Coca-Cola 500ml',
    descripcion: 'Bebida gaseosa individual',
    categoria_id: 'cat-3',
    precio_venta: 800,
    costo_produccion: 280,
    margen_ganancia: 65,
    disponible: true, agotado: false, tiempo_preparacion: 1, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[2],
  },
  {
    id: 'prod-8',
    nombre: 'Agua Mineral',
    descripcion: 'Agua mineral 500ml',
    categoria_id: 'cat-3',
    precio_venta: 500,
    costo_produccion: 120,
    margen_ganancia: 76,
    disponible: true, agotado: false, tiempo_preparacion: 1, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[2],
  },
  {
    id: 'prod-9',
    nombre: 'Combo Clásico',
    descripcion: 'Hamburguesa Clásica + Papas Medianas + Bebida 500ml',
    categoria_id: 'cat-5',
    precio_venta: 5200,
    costo_produccion: 2635,
    margen_ganancia: 49.3,
    disponible: true, agotado: false, tiempo_preparacion: 15, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[4],
  },
  {
    id: 'prod-10',
    nombre: 'Combo Bacon Premium',
    descripcion: 'Hamburguesa Bacon + Papas Grandes + Bebida 500ml',
    categoria_id: 'cat-5',
    precio_venta: 6500,
    costo_produccion: 3290,
    margen_ganancia: 49.4,
    disponible: true, agotado: false, tiempo_preparacion: 18, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[4],
  },
  {
    id: 'prod-11',
    nombre: 'Helado Artesanal',
    descripcion: 'Doble bocha con topping a elección',
    categoria_id: 'cat-4',
    precio_venta: 1500,
    costo_produccion: 580,
    margen_ganancia: 61.3,
    disponible: true, agotado: false, tiempo_preparacion: 3, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[3],
  },
  {
    id: 'prod-12',
    nombre: 'Extra Cheddar',
    descripcion: '2 fetas adicionales de cheddar',
    categoria_id: 'cat-6',
    precio_venta: 400,
    costo_produccion: 90,
    margen_ganancia: 77.5,
    disponible: true, agotado: false, tiempo_preparacion: 1, activo: true,
    created_at: '', updated_at: '',
    categoria: mockCategorias[5],
  },
];

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

export const mockMesas: Mesa[] = [
  { id: 'mesa-1', numero: 1, capacidad: 4, estado: 'pendiente_cobro', empleado_id: 'emp-1', sector: 'salon', posicion_x: 1, posicion_y: 1, activa: true, created_at: '', updated_at: '', empleado: mockEmpleados[0] },
  { id: 'mesa-2', numero: 2, capacidad: 4, estado: 'en_preparacion', empleado_id: 'emp-1', sector: 'salon', posicion_x: 2, posicion_y: 1, activa: true, created_at: '', updated_at: '', empleado: mockEmpleados[0] },
  { id: 'mesa-3', numero: 3, capacidad: 4, estado: 'libre', empleado_id: undefined, sector: 'salon', posicion_x: 3, posicion_y: 1, activa: true, created_at: '', updated_at: '' },
  { id: 'mesa-4', numero: 4, capacidad: 4, estado: 'libre', empleado_id: undefined, sector: 'salon', posicion_x: 4, posicion_y: 1, activa: true, created_at: '', updated_at: '' },
  { id: 'mesa-5', numero: 5, capacidad: 6, estado: 'ocupada', empleado_id: 'emp-2', sector: 'salon', posicion_x: 1, posicion_y: 2, activa: true, created_at: '', updated_at: '', empleado: mockEmpleados[1] },
  { id: 'mesa-6', numero: 6, capacidad: 6, estado: 'servida', empleado_id: 'emp-2', sector: 'salon', posicion_x: 2, posicion_y: 2, activa: true, created_at: '', updated_at: '', empleado: mockEmpleados[1] },
  { id: 'mesa-7', numero: 7, capacidad: 6, estado: 'libre', empleado_id: undefined, sector: 'salon', posicion_x: 3, posicion_y: 2, activa: true, created_at: '', updated_at: '' },
  { id: 'mesa-8', numero: 8, capacidad: 2, estado: 'libre', empleado_id: undefined, sector: 'barra', posicion_x: 4, posicion_y: 2, activa: true, created_at: '', updated_at: '' },
  { id: 'mesa-9', numero: 9, capacidad: 4, estado: 'en_preparacion', empleado_id: 'emp-1', sector: 'terraza', posicion_x: 1, posicion_y: 3, activa: true, created_at: '', updated_at: '', empleado: mockEmpleados[0] },
  { id: 'mesa-10', numero: 10, capacidad: 4, estado: 'libre', empleado_id: undefined, sector: 'terraza', posicion_x: 2, posicion_y: 3, activa: true, created_at: '', updated_at: '' },
  { id: 'mesa-11', numero: 11, capacidad: 4, estado: 'esperando_pedido', empleado_id: 'emp-2', sector: 'terraza', posicion_x: 3, posicion_y: 3, activa: true, created_at: '', updated_at: '', empleado: mockEmpleados[1] },
  { id: 'mesa-12', numero: 12, capacidad: 8, estado: 'libre', empleado_id: undefined, sector: 'privado', posicion_x: 4, posicion_y: 3, activa: true, created_at: '', updated_at: '' },
];

export const mockPedidoItems1: PedidoItem[] = [
  { id: 'item-1', pedido_id: 'ped-1', producto_id: 'prod-9', cantidad: 2, precio_unitario: 5200, subtotal: 10400, observaciones: 'sin cebolla', estado: 'listo', created_at: minutesAgo(40), updated_at: minutesAgo(10), producto: mockProductos[8] },
  { id: 'item-2', pedido_id: 'ped-1', producto_id: 'prod-7', cantidad: 3, precio_unitario: 800, subtotal: 2400, observaciones: '', estado: 'entregado', created_at: minutesAgo(40), updated_at: minutesAgo(15), producto: mockProductos[6] },
];

export const mockPedidos: Pedido[] = [
  {
    id: 'ped-1',
    mesa_id: 'mesa-1',
    empleado_id: 'emp-1',
    cantidad_personas: 3,
    estado: 'entregado',
    subtotal: 12800,
    descuento: 0,
    recargo: 0,
    total: 12800,
    observaciones: '',
    hora_apertura: minutesAgo(60),
    created_at: minutesAgo(60),
    updated_at: minutesAgo(10),
    mesa: mockMesas[0],
    empleado: mockEmpleados[0],
    items: mockPedidoItems1,
  },
  {
    id: 'ped-2',
    mesa_id: 'mesa-2',
    empleado_id: 'emp-1',
    cantidad_personas: 2,
    estado: 'en_preparacion',
    subtotal: 9400,
    descuento: 0,
    recargo: 0,
    total: 9400,
    observaciones: '',
    hora_apertura: minutesAgo(25),
    created_at: minutesAgo(25),
    updated_at: minutesAgo(5),
    mesa: mockMesas[1],
    empleado: mockEmpleados[0],
    items: [
      { id: 'item-3', pedido_id: 'ped-2', producto_id: 'prod-10', cantidad: 1, precio_unitario: 6500, subtotal: 6500, observaciones: 'carne bien cocida', estado: 'en_preparacion', created_at: minutesAgo(20), updated_at: minutesAgo(5), producto: mockProductos[9] },
      { id: 'item-4', pedido_id: 'ped-2', producto_id: 'prod-1', cantidad: 1, precio_unitario: 3500, subtotal: 3500, observaciones: 'extra cheddar', estado: 'en_preparacion', created_at: minutesAgo(20), updated_at: minutesAgo(5), producto: mockProductos[0] },
    ],
  },
  {
    id: 'ped-3',
    mesa_id: 'mesa-5',
    empleado_id: 'emp-2',
    cantidad_personas: 4,
    estado: 'abierto',
    subtotal: 0,
    descuento: 0,
    recargo: 0,
    total: 0,
    observaciones: '',
    hora_apertura: minutesAgo(5),
    created_at: minutesAgo(5),
    updated_at: minutesAgo(1),
    mesa: mockMesas[4],
    empleado: mockEmpleados[1],
    items: [],
  },
];

export const mockVentasSemana = [
  { dia: 'Lun', ventas: 28500, pedidos: 12 },
  { dia: 'Mar', ventas: 32100, pedidos: 15 },
  { dia: 'Mie', ventas: 41800, pedidos: 20 },
  { dia: 'Jue', ventas: 38200, pedidos: 18 },
  { dia: 'Vie', ventas: 67400, pedidos: 31 },
  { dia: 'Sab', ventas: 89200, pedidos: 42 },
  { dia: 'Dom', ventas: 75600, pedidos: 36 },
];

export const mockProductosMasVendidos = [
  { nombre: 'Combo Clásico', cantidad: 87, total: 452400 },
  { nombre: 'Combo Bacon Premium', cantidad: 64, total: 416000 },
  { nombre: 'Hamburguesa Doble', cantidad: 51, total: 280500 },
  { nombre: 'Papas Grandes', cantidad: 48, total: 86400 },
  { nombre: 'Coca-Cola 500ml', cantidad: 142, total: 113600 },
];
